const FETCH_STEPCHART_TYPES = 'FETCH_STEPCHART_TYPES';
const FETCH_COOP_STEPCHART_LEVELS = 'FETCH_COOP_STEPCHART_LEVELS';
const FETCH_STEPCHART_LEVELS = 'FETCH_STEPCHART_LEVELS';
const FETCH_ALL_STEPCHART_LEVELS = 'FETCH_ALL_STEPCHART_LEVELS';
const FETCH_REQUEST_STATUS = 'FETCH_REQUEST_STATUS';

export const commonActions = {
    FETCH_STEPCHART_TYPES, FETCH_COOP_STEPCHART_LEVELS, 
    FETCH_STEPCHART_LEVELS, FETCH_ALL_STEPCHART_LEVELS,
    FETCH_REQUEST_STATUS
}