const FETCH_REQUESTS = 'FETCH_REQUESTS';
const RECEIVED_REQUESTS = 'RECEIVED_REQUESTS';
const SAVE_SEARCH_VALUE = 'SAVE_SEARCH_VALUE'
const SET_ERROR = 'SET_ERROR';
const DISABLE_ERROR = 'DISABLE_ERROR';
const RESET_STATE = 'RESET_STATE'
const ABORT_FETCH_REQUESTS = 'ABORT_FETCH_REQUESTS';

export const requestActions = {
    FETCH_REQUESTS, RECEIVED_REQUESTS, SAVE_SEARCH_VALUE, SET_ERROR, DISABLE_ERROR, RESET_STATE, ABORT_FETCH_REQUESTS
}